fix: Don't crash when cropping account avatar or header images
The functions to return the URI for the local file for the avatar and
header images wasn't going through FileProvider.getUriForFile (e.g., as
is done in ComposeActivity) causing a `SecurityException` on newer
Android devices.

```
java.lang.SecurityException: Only content:// URIs are allowed for security reasons. Received: file://
  at com.canhub.cropper.BitmapUtils.validateOutputUri$cropper_release(BitmapUtils.kt:437)
  at com.canhub.cropper.BitmapUtils.writeBitmapToUri(BitmapUtils.kt:476)
  at com.canhub.cropper.BitmapCroppingWorkerJob$start$1$1.invokeSuspend(BitmapCroppingWorkerJob.kt:96)
  ...
```