fix(deps): update androidx.media3 to v1.3.1 (#621)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [androidx.media3:media3-ui](https://togithub.com/androidx/media) |
`1.3.0` -> `1.3.1` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/androidx.media3:media3-ui/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/androidx.media3:media3-ui/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/androidx.media3:media3-ui/1.3.0/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/androidx.media3:media3-ui/1.3.0/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[androidx.media3:media3-datasource-okhttp](https://togithub.com/androidx/media)
| `1.3.0` -> `1.3.1` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/androidx.media3:media3-datasource-okhttp/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/androidx.media3:media3-datasource-okhttp/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/androidx.media3:media3-datasource-okhttp/1.3.0/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/androidx.media3:media3-datasource-okhttp/1.3.0/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[androidx.media3:media3-exoplayer-rtsp](https://togithub.com/androidx/media)
| `1.3.0` -> `1.3.1` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/androidx.media3:media3-exoplayer-rtsp/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/androidx.media3:media3-exoplayer-rtsp/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/androidx.media3:media3-exoplayer-rtsp/1.3.0/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/androidx.media3:media3-exoplayer-rtsp/1.3.0/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[androidx.media3:media3-exoplayer-hls](https://togithub.com/androidx/media)
| `1.3.0` -> `1.3.1` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/androidx.media3:media3-exoplayer-hls/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/androidx.media3:media3-exoplayer-hls/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/androidx.media3:media3-exoplayer-hls/1.3.0/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/androidx.media3:media3-exoplayer-hls/1.3.0/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[androidx.media3:media3-exoplayer-dash](https://togithub.com/androidx/media)
| `1.3.0` -> `1.3.1` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/androidx.media3:media3-exoplayer-dash/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/androidx.media3:media3-exoplayer-dash/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/androidx.media3:media3-exoplayer-dash/1.3.0/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/androidx.media3:media3-exoplayer-dash/1.3.0/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[androidx.media3:media3-exoplayer](https://togithub.com/androidx/media)
| `1.3.0` -> `1.3.1` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/androidx.media3:media3-exoplayer/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/androidx.media3:media3-exoplayer/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/androidx.media3:media3-exoplayer/1.3.0/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/androidx.media3:media3-exoplayer/1.3.0/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

> [!WARNING]
> Some dependencies could not be looked up. Check the Dependency
Dashboard for more information.

---

### Release Notes

<details>
<summary>androidx/media (androidx.media3:media3-ui)</summary>

###
[`v1.3.1`](https://togithub.com/androidx/media/blob/HEAD/RELEASENOTES.md#131-2024-04-11)

[Compare
Source](https://togithub.com/androidx/media/compare/1.3.0...1.3.1)

This release includes the following changes since the
[1.3.0 release](#&#8203;130-2024-03-06):

-   Common Library:
- Add `Format.labels` to allow localized or other alternative labels.
-   ExoPlayer:
- Fix issue where `PreloadMediaPeriod` cannot retain the streams when it
        is preloaded again.
- Apply the correct corresponding `TrackSelectionResult` to the playing
        period in track reselection.
- Start early-enabled renderers only after advancing the playing period
        when transitioning between media items
([#&#8203;1017](https://togithub.com/androidx/media/issues/1017)).
- Add missing return type to proguard `-keepclasseswithmembers` rule for
        `DefaultVideoFrameProcessor.Factory.Builder.build()`
([#&#8203;1187](https://togithub.com/androidx/media/issues/1187)).
-   Transformer:
- Add workaround for exception thrown due to `MediaMuxer` not supporting
        negative presentation timestamps before API 30.
-   Track Selection:
- `DefaultTrackSelector`: Prefer video tracks with a 'reasonable' frame
rate (>=10fps) over those with a lower or unset frame rate. This ensures
the player selects the 'real' video track in MP4s extracted from motion
        photos that can contain two HEVC tracks where one has a higher
        resolution but a very small number of frames
([#&#8203;1051](https://togithub.com/androidx/media/issues/1051)).
-   Extractors:
- Fix issue where padding was not skipped when reading odd-sized chunks
from WAV files
([#&#8203;1117](https://togithub.com/androidx/media/pull/1117)).
- MP3: Populate `Format.averageBitrate` from metadata frames such as
        `XING` and `VBRI`.
- MPEG-TS: Revert a change that aimed to ensure the last frame is
rendered
        by passing the last access unit of a stream to the sample queue
([#&#8203;7909](https://togithub.com/google/ExoPlayer/issues/7909)).
This is due
        to the change causing new problems with I-frame only HLS streams
([#&#8203;1150](https://togithub.com/google/ExoPlayer/issues/1150)) and
H.262 HLS
streams
([#&#8203;1126](https://togithub.com/google/ExoPlayer/issues/1126)).
-   Audio:
- Allow renderer recovery by disabling offload if audio track fails to
        initialize in offload mode.
-   Video:
- Add workaround for a device issue on Galaxy Tab S7 FE, Chromecast with
Google TV, and Lenovo M10 FHD Plus that causes 60fps H265 streams to be
        marked as unsupported
- Add workaround that ensures the first frame is always rendered while
tunneling even if the device does not do this automatically as required
by the API
([#&#8203;1169](https://togithub.com/androidx/media/issues/1169)).
        ([#&#8203;966](https://togithub.com/androidx/media/issues/966)).
- Fix issue where HDR color info handling causes codec misbehavior and
        prevents adaptive format switches for SDR video tracks
([#&#8203;1158](https://togithub.com/androidx/media/issues/1158)).
-   Text:
    -   WebVTT: Prevent directly consecutive cues from creating spurious
        additional `CuesWithTiming` instances from `WebvttParser.parse`
([#&#8203;1177](https://togithub.com/androidx/media/issues/1177)).
-   DRM:
- Work around a `NoSuchMethodError` which can be thrown by the
`MediaDrm`
        framework instead of `ResourceBusyException` or
        `NotProvisionedException` on some Android 14 devices
([#&#8203;1145](https://togithub.com/androidx/media/issues/1145)).
-   Effect:
    -   Improved PQ to SDR tone-mapping by converting color spaces.
-   Session:
- Fix issue where the current position jumps back when the controller
        replaces the current item
        ([#&#8203;951](https://togithub.com/androidx/media/issues/951)).
- Fix issue where `MediaMetadata` with just non-null `extras` is not
        transmitted between media controllers and sessions
([#&#8203;1176](https://togithub.com/androidx/media/issues/1176)).
-   UI:
    -   Fallback to include audio track language name if `Locale` cannot
        identify a display name
        ([#&#8203;988](https://togithub.com/androidx/media/issues/988)).
-   DASH Extension:
- Populate all `Label` elements from the manifest into `Format.labels`
        ([#&#8203;1054](https://togithub.com/androidx/media/pull/1054)).
-   RTSP Extension:
    -   Skip empty session information values (i-tags) in SDP parsing
([#&#8203;1087](https://togithub.com/androidx/media/issues/1087)).
-   Decoder Extensions (FFmpeg, VP9, AV1, MIDI, etc.):
- Disable the MIDI extension as a local dependency by default because it
requires an additional Maven repository to be configured. Users who need
        this module from a local dependency
[can re-enable
it](https://togithub.com/androidx/media/blob/main/README.md#midi-module).

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/pachli/pachli-android).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy4yOTMuMCIsInVwZGF0ZWRJblZlciI6IjM3LjI5My4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>